backend:
  name: git-gateway # Set to github when deploying
  branch: main # Branch to update (optional; defaults to main)
media_folder: "public/images"
public_folder: "/images"
logo_url: /logo.png
# when using the default proxy server port
local_backend: true
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Publish Date",
              name: "date",
              widget: "datetime",
              required: true,
            }
          - label: "Partners"
            name: "partners"
            widget: "list"
            collapsed: true
            minimize_collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - {
                  label: "Logo",
                  name: "logo",
                  widget: "image",
                  choose_url: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
      - label: "Admin"
        name: "admin"
        file: "content/pages/admin.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Lexicons"
        name: "lexicons"
        file: "content/pages/lexicons.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Publish Date",
              name: "date",
              widget: "datetime",
              required: true,
            }
          - label: "Resources"
            name: "resouces"
            widget: "list"
            collapsed: true
            minimize_collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - {
                  label: "Thumbnail",
                  name: "thumbnail",
                  widget: "image",
                  choose_url: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
              - {
                  label: "Call to Action",
                  name: "cta",
                  widget: "string",
                  default: "Visit website",
                }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Footer"
        name: "footer"
        file: "content/settings/footer.md"
        fields:
          - label: "Project"
            name: "project"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - {
                  label: "Logo",
                  name: "logo",
                  widget: "image",
                  choose_url: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
          - label: "Stay in Touch"
            name: "contacts"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Social Media"
                name: "socialMedia"
                widget: "list"
                collapsed: true
                minimize_collapsed: true
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
                  - {
                      label: "Logo",
                      name: "logo",
                      widget: "image",
                      choose_url: true,
                    }
          - label: "Quick Links"
            name: "quickLinks"
            required: false
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                collapsed: true
                minimize_collapsed: true
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
