backend:
  name: git-gateway # Set to github when deploying
  branch: main # Branch to update (optional; defaults to main)
media_folder: "public/images"
public_folder: "/images"
logo_url: /logo.png
# when using the default proxy server port
local_backend: true
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - {
              label: "Description",
              name: "description",
              widget: "markdown",
              required: true,
            }
          - {
              label: "Publish Date",
              name: "date",
              widget: "datetime",
              required: true,
            }
